apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v5
        env:
        - name: GET_HOSTS_FROM
          value: "redis-leader"
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80
