apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  labels:
    app: redis
    role: replica
    tier: backned
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: replica
        tier: backend
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redis-follower:v2
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 6379
